import {readFile} from 'node:fs/promises';
export const merchandisingName="Outils d'aide au merchandising";
export const tgPositions=[[43.078, 25.472], [43.929, 40.263], [43.929, 52.588], [43.929, 64.914], [31.787, 25.472], [20.572, 25.472], [23.357, 40.263], [23.357, 52.588], [8.739, 31.224], [8.739, 42.728]];
export const icPositions=[[79.35, 27.116], [79.35, 33.279], [79.35, 39.441], [79.35, 45.604], [79.35, 60.394], [79.35, 66.311], [79.35, 72.309], [79.35, 77.896]];
export const zonePositions=[...tgPositions,...icPositions];
export function validateTG(body){if(!Number.isInteger(body?.id)||body.id<1||body.id>zonePositions.length||!Number.isInteger(body.revision)||body.revision<0)throw Object.assign(Error('Zone ou version invalide.'),{status:400});if(typeof body.name!=='string'||!body.name.trim()||body.name.trim().length>120||typeof body.comment!=='string'||body.comment.length>5000)throw Object.assign(Error('Renseignez un nom (120 caractères maximum) et un commentaire (5 000 caractères maximum).'),{status:400});const months=body.months??{};if(!months||Array.isArray(months)||typeof months!=='object'||Object.keys(months).length>120||Object.entries(months).some(([k,v])=>!/^20\d{2}-(0[1-9]|1[0-2])$/.test(k)||typeof v!=='string'||v.length>3000))throw Object.assign(Error('Planning mensuel invalide (120 mois maximum, 3 000 caractères par mois).'),{status:400});return {...body,months,name:body.name.trim()};}
export function registerMerchandising({app,db,auth,ready,csrf,viewUniverse,editUniverse,fail}){const view=viewUniverse(merchandisingName),edit=editUniverse(merchandisingName);
app.get('/api/merchandising/plan',auth,ready,view,async(req,res)=>{res.type('jpeg').send(Buffer.from(await readFile(new URL('./merchandising-plan.b64',import.meta.url),'utf8'),'base64'));});
app.get('/api/merchandising',auth,ready,view,async(req,res)=>{const stored=(await db.query('SELECT id,name,comment,months,revision FROM merchandising_zones ORDER BY id')).rows;res.json({canEdit:true,zones:zonePositions.map(([x,y],i)=>({id:i+1,x,y,code:i<10?'TG'+(i+1):'IC'+(i-9),name:i<10?'TG'+(i+1):'IC'+(i-9),comment:'',months:{},revision:0,...stored.find(r=>r.id===i+1)}))});});
app.put('/api/merchandising/:id',auth,ready,edit,csrf,async(req,res)=>{const b=validateTG({...req.body,id:Number(req.params.id)});const r=b.revision===0?await db.query('INSERT INTO merchandising_zones(id,name,comment,revision,months) VALUES($1,$2,$3,1,$4::jsonb) ON CONFLICT(id) DO NOTHING RETURNING id,name,comment,months,revision',[b.id,b.name,b.comment,JSON.stringify(b.months)]):await db.query('UPDATE merchandising_zones SET name=$2,comment=$3,months=COALESCE($5::jsonb,months),revision=revision+1 WHERE id=$1 AND revision=$4 RETURNING id,name,comment,months,revision',[b.id,b.name,b.comment,b.revision,req.body.months===undefined?null:JSON.stringify(b.months)]);if(!r.rows.length)throw fail(409,'Cette zone a changé. Rechargez le plan avant de modifier sa fiche.');res.json(r.rows[0]);});}
