import {createCodeSheet} from './order-code-sheet.mjs';
import {randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import QRCode from 'qrcode';
import {encrypt,decrypt,digest,verifyPassword} from './security.mjs';
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export const orderIdleMs=10*60*1000;
export function base32(bytes){let bits=0,value=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)out+=alphabet[(value<<(5-bits))&31];return out;}
function decode(value){let bits=0,n=0,out=[];for(const ch of value){const v=alphabet.indexOf(ch);if(v<0)throw Error('Secret TOTP invalide.');n=(n<<5)|v;bits+=5;if(bits>=8){out.push((n>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
export function totp(secret,step,digits=6){const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(step));const hash=createHmac('sha1',decode(secret)).update(counter).digest(),offset=hash[hash.length-1]&15;return String((hash.readUInt32BE(offset)&0x7fffffff)%10**digits).padStart(digits,'0');}
export function matchTotp(secret,code,timestamp,lastStep=-1){if(typeof code!=='string'||!/^\d{6}$/.test(code))return null;const current=Math.floor(timestamp/30000);for(const step of [current,current-1,current+1])if(step>Number(lastStep)&&step>=0&&timingSafeEqual(Buffer.from(totp(secret,step)),Buffer.from(code)))return step;return null;}
const recoveryValue=value=>typeof value==='string'?value.replace(/[\s-]/g,'').toUpperCase():'';
function recovery(){const codes=Array.from({length:10},()=>randomBytes(10).toString('hex').toUpperCase().match(/.{1,5}/g).join('-'));return {codes,hashes:codes.map(c=>digest(recoveryValue(c)))};}
export function registerOrderMFA({app,db,auth,ready,csrf,viewUniverse,fail,secret,now=()=>Date.now()}){
 const access=viewUniverse("Outils d'aide aux commandes"),read=[auth,ready,access],write=[...read,csrf];
 const required=()=>Object.assign(fail(403,'Déverrouillez les commandes avec votre fiche de codes ou 2FAS Auth.'),{code:'MFA_REQUIRED'});
 async function audit(client,userId,actorId,action,details=''){await client.query('INSERT INTO order_mfa_audit(user_id,actor_id,action,details) VALUES($1,$2,$3,$4)',[userId,actorId,action,details]);}
 async function transaction(work){const client=db.connect?await db.connect():db;try{await client.query('BEGIN');const result=await work(client);await client.query('COMMIT');return result;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release?.();}}
 async function attempt(userId){const key=digest('order-mfa:'+userId),row=(await db.query("INSERT INTO login_attempts(key,count,until_at) VALUES($1,1,now()+interval '15 minutes') ON CONFLICT(key) DO UPDATE SET count=CASE WHEN login_attempts.until_at<now() THEN 1 ELSE login_attempts.count+1 END,until_at=CASE WHEN login_attempts.until_at<now() THEN EXCLUDED.until_at ELSE login_attempts.until_at END RETURNING count",[key])).rows[0];if(row.count>5)throw fail(429,'Trop de tentatives. Réessayez dans 15 minutes.');}
 async function clearAttempts(userId){await db.query('DELETE FROM login_attempts WHERE key=$1',[digest('order-mfa:'+userId)]);}
 async function password(req){if(!req.auth.password_hash||!await verifyPassword(req.body?.password,req.auth.password_hash))throw fail(400,'Mot de passe personnel incorrect.');}
 async function grant(client,req,generation){const row=(await client.query('UPDATE sessions SET order_mfa_at=$2,order_mfa_generation=$3 WHERE id=$1 AND user_id=$4 RETURNING id',[req.auth.session_id,new Date(now()),generation,req.auth.id])).rows[0];if(!row)throw fail(401,'Reconnectez-vous au portail.');}
 async function guard(req,res,next){try{const row=(await db.query("UPDATE sessions s SET order_mfa_at=$3 FROM order_mfa f WHERE s.id=$1 AND s.user_id=$2 AND f.user_id=s.user_id AND (f.secret IS NOT NULL OR f.paper_enabled=TRUE) AND s.order_mfa_generation=f.generation AND s.order_mfa_at>$3::timestamptz-interval '10 minutes' RETURNING s.id",[req.auth.session_id,req.auth.id,new Date(now())])).rows[0];if(!row)throw required();next();}catch(e){next(e);}}
 app.get('/api/order-mfa/status',...read,async(req,res)=>{const row=(await db.query('SELECT secret,generation,paper_enabled,paper_hashes,paper_reference FROM order_mfa WHERE user_id=$1',[req.auth.id])).rows[0],session=(await db.query('SELECT order_mfa_at,order_mfa_generation FROM sessions WHERE id=$1 AND user_id=$2',[req.auth.session_id,req.auth.id])).rows[0];const configured=!!row?.secret||!!row?.paper_enabled,unlocked=configured&&session?.order_mfa_generation===row.generation&&now()-new Date(session.order_mfa_at).getTime()<orderIdleMs&&!!session.order_mfa_at;res.json({configured,totpConfigured:!!row?.secret,paperConfigured:!!row?.paper_enabled,paperRemaining:row?.paper_hashes?.length||0,paperReference:row?.paper_reference||null,unlocked,idleSeconds:600,lastActivityAt:unlocked?session.order_mfa_at:null,isAdmin:req.auth.role==='admin'});});
 app.post('/api/order-mfa/setup',...write,async(req,res)=>{await attempt(req.auth.id);await password(req);const current=(await db.query('SELECT * FROM order_mfa WHERE user_id=$1',[req.auth.id])).rows[0];if(current?.paper_enabled)await requireUnlocked(req);const value=base32(randomBytes(20)),expires=new Date(now()+orderIdleMs),row=(await db.query("INSERT INTO order_mfa(user_id,pending_secret,pending_session,pending_expires) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET pending_secret=EXCLUDED.pending_secret,pending_session=EXCLUDED.pending_session,pending_expires=EXCLUDED.pending_expires WHERE order_mfa.secret IS NULL RETURNING user_id",[req.auth.id,encrypt(value,secret),req.auth.session_id,expires])).rows[0];if(!row)throw fail(409,'2FAS Auth est déjà activé pour votre compte.');const label='PORTAIL + Commandes:'+req.auth.email,uri='otpauth://totp/'+encodeURIComponent(label)+'?secret='+value+'&issuer='+encodeURIComponent('PORTAIL + Commandes')+'&algorithm=SHA1&digits=6&period=30';const qr=await QRCode.toDataURL(uri,{errorCorrectionLevel:'M',width:280,margin:2});await clearAttempts(req.auth.id);res.json({qr,secret:value,expiresAt:expires});});
 app.post('/api/order-mfa/confirm',...write,async(req,res)=>{await attempt(req.auth.id);const result=await transaction(async client=>{const row=(await client.query('SELECT * FROM order_mfa WHERE user_id=$1 FOR UPDATE',[req.auth.id])).rows[0];if(!row||row.secret||row.pending_session!==req.auth.session_id||!row.pending_expires||new Date(row.pending_expires).getTime()<=now())throw fail(409,'La configuration a expiré. Recommencez l’activation.');const value=decrypt(row.pending_secret,secret),step=matchTotp(value,req.body?.code,now());if(step===null)throw fail(400,'Code incorrect. Vérifiez l’heure de votre téléphone et utilisez le code actuel.');const backup=recovery();await client.query('UPDATE order_mfa SET secret=$2,pending_secret=NULL,pending_session=NULL,pending_expires=NULL,last_step=$3,recovery_hashes=$4::jsonb,updated_at=now() WHERE user_id=$1',[req.auth.id,encrypt(value,secret),step,JSON.stringify(backup.hashes)]);await grant(client,req,row.generation);await audit(client,req.auth.id,req.auth.id,'setup');return backup.codes;});await clearAttempts(req.auth.id);res.json({ok:true,recoveryCodes:result});});
 async function factor(client,req){const row=(await client.query('SELECT * FROM order_mfa WHERE user_id=$1 FOR UPDATE',[req.auth.id])).rows[0];if(!row?.secret&&!row?.paper_enabled)throw fail(409,'Créez votre fiche de codes ou activez 2FAS Auth.');if(req.body?.paperCode){await password(req);const value=recoveryValue(req.body.paperCode);if(!/^[A-F0-9]{16}$/.test(value))throw fail(400,'Code de fiche invalide.');const hashes=[...(row.paper_hashes||[])],index=hashes.indexOf(digest(value));if(index<0)throw fail(400,'Code incorrect, déjà utilisé ou ancienne fiche.');hashes.splice(index,1);await client.query('UPDATE order_mfa SET paper_hashes=$2::jsonb,updated_at=now() WHERE user_id=$1',[req.auth.id,JSON.stringify(hashes)]);return {row,paper:true};}if(req.body?.recoveryCode){await password(req);const value=recoveryValue(req.body.recoveryCode);if(!/^[A-F0-9]{20}$/.test(value))throw fail(400,'Code de secours invalide.');const hashes=row.recovery_hashes||[],hash=digest(value),index=hashes.findIndex(h=>timingSafeEqual(Buffer.from(h),Buffer.from(hash)));if(index<0)throw fail(400,'Code de secours incorrect ou déjà utilisé.');hashes.splice(index,1);await client.query('UPDATE order_mfa SET recovery_hashes=$2::jsonb,updated_at=now() WHERE user_id=$1',[req.auth.id,JSON.stringify(hashes)]);return {row,recovery:true};}if(!row.secret)throw fail(400,'2FAS Auth n’est pas activé pour votre compte.');const step=matchTotp(decrypt(row.secret,secret),req.body?.code,now(),row.last_step);if(step===null)throw fail(400,'Code incorrect ou déjà utilisé. Attendez le prochain code 2FAS Auth.');await client.query('UPDATE order_mfa SET last_step=$2,updated_at=now() WHERE user_id=$1',[req.auth.id,step]);return {row,recovery:false};}
 app.post('/api/order-mfa/unlock',...write,async(req,res)=>{await attempt(req.auth.id);await transaction(async client=>{const checked=await factor(client,req);await grant(client,req,checked.row.generation);await audit(client,req.auth.id,req.auth.id,checked.paper?'paper-unlock':checked.recovery?'recovery':'unlock');});await clearAttempts(req.auth.id);res.json({ok:true});});
 app.post('/api/order-mfa/touch',...write,guard,(req,res)=>res.json({ok:true}));
 app.post('/api/order-mfa/lock',...write,async(req,res)=>{await db.query('UPDATE sessions SET order_mfa_at=NULL,order_mfa_generation=0 WHERE id=$1 AND user_id=$2',[req.auth.session_id,req.auth.id]);res.json({ok:true});});
 app.post('/api/order-mfa/recovery',...write,guard,async(req,res)=>{await attempt(req.auth.id);await password(req);const codes=await transaction(async client=>{await factor(client,req);const backup=recovery();await client.query('UPDATE order_mfa SET recovery_hashes=$2::jsonb,updated_at=now() WHERE user_id=$1',[req.auth.id,JSON.stringify(backup.hashes)]);await audit(client,req.auth.id,req.auth.id,'recovery-renewed');return backup.codes;});await clearAttempts(req.auth.id);res.json({ok:true,recoveryCodes:codes});});
 const admin=(req,res,next)=>req.auth.role==='admin'?next():next(fail(403,'Réservé aux administrateurs.'));
 app.get('/api/order-mfa/users',...read,admin,guard,async(req,res)=>res.json((await db.query('SELECT u.id,u.name,(f.secret IS NOT NULL OR f.paper_enabled=TRUE) AS configured FROM users u LEFT JOIN order_mfa f ON f.user_id=u.id WHERE u.active=TRUE ORDER BY u.name')).rows));
 app.post('/api/order-mfa/reset',...write,admin,guard,async(req,res)=>{const id=req.body?.userId,reason=req.body?.reason;if(!Number.isSafeInteger(id)||id<1||id===req.auth.id||typeof reason!=='string'||reason.trim().length<10||reason.length>500)throw fail(400,'Choisissez un autre collaborateur et indiquez le motif (10 à 500 caractères).');await attempt(req.auth.id);await password(req);await transaction(async client=>{const row=(await client.query('UPDATE order_mfa SET secret=NULL,pending_secret=NULL,pending_session=NULL,pending_expires=NULL,last_step=-1,recovery_hashes=\'[]\',paper_enabled=FALSE,paper_hashes=\'[]\',paper_reference=NULL,generation=generation+1,updated_at=now() WHERE user_id=$1 RETURNING user_id',[id])).rows[0];if(!row)throw fail(404,'Ce collaborateur n’a pas configuré son accès sécurisé.');await client.query('UPDATE sessions SET order_mfa_at=NULL,order_mfa_generation=0 WHERE user_id=$1',[id]);await audit(client,id,req.auth.id,'admin-reset',reason.trim());});await clearAttempts(req.auth.id);res.json({ok:true});});

 async function requireUnlocked(req){await new Promise((resolve,reject)=>guard(req,null,e=>e?reject(e):resolve()));}
 app.post('/api/order-mfa/paper',...write,async(req,res)=>{
  await attempt(req.auth.id);await password(req);
  const result=await transaction(async client=>{
   await client.query('INSERT INTO order_mfa(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING',[req.auth.id]);
   const row=(await client.query('SELECT * FROM order_mfa WHERE user_id=$1 FOR UPDATE',[req.auth.id])).rows[0];
   const generation=row.generation+1;if(row.secret||row.paper_enabled)await factor(client,req);
   const codes=Array.from({length:50},()=>randomBytes(8).toString('hex').toUpperCase().match(/.{4}/g).join('-')),hashes=codes.map(c=>digest(recoveryValue(c))),reference=randomBytes(5).toString('hex').toUpperCase();
   const pdf=await createCodeSheet({codes,name:req.auth.name,email:req.auth.email,reference});
   await client.query('UPDATE order_mfa SET paper_enabled=TRUE,paper_hashes=$2::jsonb,paper_reference=$3,generation=generation+1,updated_at=now() WHERE user_id=$1',[req.auth.id,JSON.stringify(hashes),reference]);
   await client.query('UPDATE sessions SET order_mfa_at=NULL,order_mfa_generation=0 WHERE user_id=$1',[req.auth.id]);
   await grant(client,req,generation);await audit(client,req.auth.id,req.auth.id,'paper-created',reference);
   return {codes,reference,pdf:pdf.toString('base64')};
  });await clearAttempts(req.auth.id);res.json(result);
 });
 app.post('/api/order-mfa/totp-disable',...write,async(req,res)=>{
  await attempt(req.auth.id);await password(req);await transaction(async client=>{
   const checked=await factor(client,req),row=checked.row,generation=row.generation+1;
   // A consumed paper code may have been the last one; inspect the updated record.
   const current=(await client.query('SELECT * FROM order_mfa WHERE user_id=$1 FOR UPDATE',[req.auth.id])).rows[0];
   if(!current.paper_enabled||!current.paper_hashes?.length)throw fail(400,'Conservez une fiche avec des codes disponibles avant de désactiver 2FAS.');
   await client.query("UPDATE order_mfa SET secret=NULL,pending_secret=NULL,pending_session=NULL,pending_expires=NULL,last_step=-1,recovery_hashes='[]',generation=generation+1,updated_at=now() WHERE user_id=$1",[req.auth.id]);
   await client.query('UPDATE sessions SET order_mfa_at=NULL,order_mfa_generation=0 WHERE user_id=$1',[req.auth.id]);await grant(client,req,generation);await audit(client,req.auth.id,req.auth.id,'totp-disabled');
  });await clearAttempts(req.auth.id);res.json({ok:true});
 });
 return {guard};
}
