export function registerProcedures({app,db,auth,ready,csrf,viewUniverse,editUniverse,fail,publish}){
 const fields={category:100,title:200,description:1500,keywords:500,url:1000};
 function validate(body){const d={};for(const [k,max] of Object.entries(fields)){const v=body?.[k]??'';if(typeof v!=='string'||v.length>max)throw fail(400,'Champ invalide : '+k);d[k]=v.trim();}if(!d.title||!d.category||!d.url)throw fail(400,'Le titre, l’application et le lien sont obligatoires.');try{const u=new URL(d.url);if(u.protocol!=='https:'||!['drive.google.com','docs.google.com'].includes(u.hostname)||u.username||u.password)throw Error();}catch{throw fail(400,'Utilisez un lien HTTPS Google Drive ou Google Docs.');}return d;}
 const guard=[auth,ready,editUniverse('Procédures'),csrf];
 app.get('/api/procedures',auth,ready,viewUniverse('Procédures'),async(req,res)=>res.json((await db.query('SELECT id,category,title,description,keywords,url,created_at FROM procedure_documents WHERE active=TRUE ORDER BY lower(category),lower(title),id')).rows));
 app.post('/api/procedures',...guard,async(req,res)=>{const d=validate(req.body);const row=(await db.query('INSERT INTO procedure_documents(category,title,description,keywords,url) VALUES($1,$2,$3,$4,$5) RETURNING *',Object.keys(fields).map(k=>d[k]))).rows[0];await publish('Procédures','Document ajouté : '+d.title);res.status(201).json(row);});
 app.put('/api/procedures/:id',...guard,async(req,res)=>{const d=validate(req.body);const row=(await db.query('UPDATE procedure_documents SET category=$1,title=$2,description=$3,keywords=$4,url=$5 WHERE id=$6 AND active=TRUE RETURNING *',[...Object.keys(fields).map(k=>d[k]),req.params.id])).rows[0];if(!row)throw fail(404,'Document introuvable.');res.json(row);});
 app.delete('/api/procedures/:id',...guard,async(req,res)=>{const row=(await db.query('UPDATE procedure_documents SET active=FALSE WHERE id=$1 AND active=TRUE RETURNING id',[req.params.id])).rows[0];if(!row)throw fail(404,'Document introuvable.');res.json({ok:true});});
 app.post('/api/procedures/:id/restore',...guard,async(req,res)=>{const row=(await db.query('UPDATE procedure_documents SET active=TRUE WHERE id=$1 AND active=FALSE RETURNING id',[req.params.id])).rows[0];if(!row)throw fail(404,'Document introuvable.');res.json({ok:true});});
}
