CREATE TABLE IF NOT EXISTS users (
 id SERIAL PRIMARY KEY, name TEXT NOT NULL, job TEXT NOT NULL DEFAULT '',
 email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'employee' CHECK(role IN ('admin','employee')),
 rights JSONB NOT NULL DEFAULT '[]', must_change BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS sessions (
 id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 csrf TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, oauth_state TEXT, oauth_expires TIMESTAMPTZ, oauth_verifier TEXT
);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS calendar_cache (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK(singleton), events JSONB NOT NULL, synced_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts (key TEXT PRIMARY KEY, count INTEGER NOT NULL, until_at TIMESTAMPTZ NOT NULL);

CREATE TABLE IF NOT EXISTS music_tracks (
 id SERIAL PRIMARY KEY,
 artist TEXT NOT NULL CHECK(length(artist) BETWEEN 1 AND 200),
 title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 200),
 track_key TEXT NOT NULL UNIQUE,
 contributor TEXT NOT NULL DEFAULT '',
 added_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
 source TEXT NOT NULL DEFAULT 'collaborateur',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS publications (
 id BIGSERIAL PRIMARY KEY, universe TEXT NOT NULL, title TEXT NOT NULL,
 source_key TEXT UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS publications_universe_id ON publications(universe,id DESC);
CREATE TABLE IF NOT EXISTS publication_reads (
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 universe TEXT NOT NULL, last_id BIGINT NOT NULL DEFAULT 0,
 PRIMARY KEY(user_id,universe)
);
CREATE TABLE IF NOT EXISTS schedule_weeks (
 week DATE PRIMARY KEY CHECK(EXTRACT(ISODOW FROM week)=1),
 draft JSONB NOT NULL DEFAULT '{}', published JSONB,
 revision INTEGER NOT NULL DEFAULT 0, published_revision INTEGER,
 published_at TIMESTAMPTZ
);
