import {PDFDocument,StandardFonts} from 'pdf-lib';
export const absenceKinds=['conge','maladie','recuperation','absence_injustifiee','absence'];
export function monthBounds(month){if(typeof month!=='string'||!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))throw Object.assign(Error('Mois invalide.'),{status:400});const start=month+'-01',d=new Date(start+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);return {start,end:d.toISOString().slice(0,10)};}
export function summarizeMonth(people,entries,month){const {start,end}=monthBounds(month);return people.map(p=>{const row={...p,actualMinutes:0,missingDays:0,mealTickets:0,absences:Object.fromEntries(absenceKinds.map(k=>[k,0]))};for(const e of entries){if(e.userId!==p.id||e.day<start||e.day>=end)continue;if(['travail','formation','ecole_cfa'].includes(e.kind)){if(Number.isInteger(e.actualMinutes))row.actualMinutes+=e.actualMinutes;else row.missingDays++;}if(e.mealTicket)row.mealTickets++;if(absenceKinds.includes(e.kind))row.absences[e.kind]++;}return row;});}
export async function monthPdf(data){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page,y;const clean=s=>String(s).replace(/[^\x20-\xff]/g,'?');function text(s,x,size=10,b=false){page.drawText(clean(s),{x,y,size,font:b?bold:font});}function newPage(){page=pdf.addPage([841.89,595.28]);y=555;text('Pharmacie de Trevoux - Recapitulatif mensuel '+data.month,32,16,true);y-=25;text('Heures realisees saisies par l’administrateur. Absences en jours, hors repos.',32);y-=18;text('Source : brouillons administrateur. Verifier les jours non renseignes avant transmission.',32);y-=18;text('Cabinet comptable : '+(data.accountantEmail||'adresse non renseignee'),32);y-=28;['Collaborateur','Heures','A saisir','Conges','Maladie','Recup.','Injust.','Autres','Tickets'].forEach((s,i)=>text(s,[32,275,340,405,470,535,600,665,730][i],10,true));y-=24;}
newPage();for(const r of data.rows){if(y<55)newPage();let name=clean(r.name);while(font.widthOfTextAtSize(name,10)>230)name=name.slice(0,-1);const values=[name,`${Math.floor(r.actualMinutes/60)}h${String(r.actualMinutes%60).padStart(2,'0')}`,r.missingDays,...absenceKinds.map(k=>r.absences[k]),r.mealTickets];values.forEach((s,i)=>text(s,[32,275,340,405,470,535,600,665,730][i]));y-=24;}for(const [i,p]of pdf.getPages().entries())p.drawText(`${i+1} / ${pdf.getPageCount()}`,{x:760,y:22,size:9,font});return Buffer.from(await pdf.save());}
export function registerScheduleMonth({app,db,auth,ready,admin,csrf,access,roster,fail}){async function report(month){const {start,end}=monthBounds(month),d=new Date(start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));const first=d.toISOString().slice(0,10);const [people,result,email]=await Promise.all([roster(),db.query('SELECT draft FROM schedule_weeks WHERE week >= $1::date AND week < $2::date ORDER BY week',[first,end]),db.query("SELECT value FROM settings WHERE key='schedule_accountant_email'")]);return {month,accountantEmail:email.rows[0]?.value||'',rows:summarizeMonth(people,result.rows.flatMap(r=>Object.values(r.draft||{})),month)};}
app.get('/api/schedule-month',auth,ready,admin,access,async(req,res)=>res.json(await report(req.query.month)));
app.put('/api/schedule-month/accountant',auth,ready,admin,access,csrf,async(req,res)=>{const email=req.body.email?.trim();if(typeof email!=='string'||email.length>254||(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)))throw fail(400,'Adresse e-mail invalide.');await db.query('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',['schedule_accountant_email',email]);res.json({ok:true});});
app.get('/api/schedule-month/pdf',auth,ready,admin,access,async(req,res)=>{const data=await report(req.query.month);res.set('Content-Type','application/pdf').set('Cache-Control','no-store').set('Content-Disposition',`attachment; filename="recapitulatif-${data.month}.pdf"`).send(await monthPdf(data));});}
