import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {PDFDocument} from 'pdf-lib';
import {validateChallenge,cleanAnalysis,progress,earnedGain,extractChallengePDF,registerChallenges} from '../challenges.mjs';import {documentMessage,createInvitationMailer} from '../invitations.mjs';import {encrypt} from '../security.mjs';
const fail=(status,message)=>Object.assign(Error(message),{status}),challenge={month:'2026-10',title:'Vitamine C',laboratoryId:1,modalities:'Produits vitamine C — CA TTC',metric:'units',target:100,gainPerCollaborator:25,participants:[{id:2,name:'Alice',target:40},{id:3,name:'Bob',target:60}]};
test('Challenges : mois civil, participants sans objectifs individuels et gain contrôlés',()=>{assert.equal(validateChallenge(challenge,fail).month,'2026-10');for(const bad of [{month:'2026-13'},{month:'2026-10-01'},{target:0},{target:100.5},{gainPerCollaborator:-1},{gainPerCollaborator:1.001},{gainPerCollaborator:NaN},{participants:[{id:2,target:50},{id:2,target:50}]}])assert.throws(()=>validateChallenge({...challenge,...bad},fail));assert.equal(validateChallenge({...challenge,metric:'revenue',target:100.5,participants:[{id:2,target:40.25},{id:3,target:60.25}]},fail).target,100.5);});
test('Challenges : inconnu distinct de zéro, progression au-delà de 100 % et gain collectif',()=>{assert.equal(progress(null,100),null);assert.equal(progress(0,100),0);assert.equal(progress(40,100),40);assert.equal(progress(150,100),150);for(const value of [null,0,99,99.99])assert.equal(earnedGain(value,100,25),0);for(const value of [100,101,150])assert.equal(earnedGain(value,100,25),25);assert.deepEqual(validateChallenge({...challenge,participants:[{id:2}]},fail).participants,[{id:2}]);const partial=cleanAnalysis({global:null,participants:[{id:2,value:0}],notes:[]},challenge,fail);assert.equal(partial.global,null);assert.equal(partial.participants[1].value,null);const complete=cleanAnalysis({global:null,participants:[{id:2,value:40},{id:3,value:60}],notes:[]},challenge,fail);assert.equal(complete.global,100);assert.equal(cleanAnalysis({...complete,global:110},challenge,fail).notes.length,1);assert.throws(()=>cleanAnalysis({global:2,participants:[{id:99,value:2}],notes:[]},challenge,fail));assert.throws(()=>cleanAnalysis({global:2.5,participants:[],notes:[]},challenge,fail));});
test('Challenges : lecture PDF structurée, périmètre et refus API',async()=>{let request;const fetchImpl=async(url,args)=>{request=JSON.parse(args.body);return {ok:true,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({global:50,participants:[{id:2,value:20},{id:3,value:30}],notes:[]})}]}]})};};const result=await extractChallengePDF({file:{bytes:Buffer.from('%PDF')},challenge:{...challenge,laboratoryName:'Labo'},key:'test',fetchImpl,fail});assert.equal(result.global,50);assert.equal(request.store,false);assert.equal(request.text.format.strict,true);assert.match(request.instructions,/N’invente aucune valeur/);assert.equal(request.input[0].content[1].type,'input_file');assert.match(request.input[0].content[0].text,/2026-10/);await assert.rejects(()=>extractChallengePDF({file:{bytes:Buffer.from('pdf')},challenge,key:'test',fail,fetchImpl:async()=>({ok:false,status:401})}),/clé OpenAI/);});
test('Challenges : pièce jointe exacte et Gmail pharmacie',async()=>{const bytes=Buffer.from('%PDF-1.7\nreport\n%%EOF'),raw=documentMessage({sender:'pharmacie.trevoux@gmail.com',email:'lab@example.test',subject:'Bilan — octobre',text:'Bonjour',fileName:'bilan octobre.pdf',bytes}).raw,mime=Buffer.from(raw,'base64url').toString();assert.match(mime,/multipart\/mixed/);assert.match(mime,/Content-Type: application\/pdf/);assert.match(mime,/To: lab@example.test/);assert.ok(mime.includes(bytes.toString('base64')));assert.throws(()=>documentMessage({sender:'pharmacie.trevoux@gmail.com',email:'lab@example.test\r\nBcc: other@test.fr',subject:'Bilan',text:'',fileName:'x.pdf',bytes}));let sent;const mailer=createInvitationMailer({getSetting:async()=>encrypt({sender:'pharmacie.trevoux@gmail.com',scope:'https://www.googleapis.com/auth/gmail.send',access_token:'token',expires_at:Date.now()+3600000},'test'),setSetting:async()=>{},secret:'test',clientId:'id',clientSecret:'secret',fail,fetchImpl:async(url,args)=>{sent=JSON.parse(args.body);return {ok:true,json:async()=>({id:'gmail-id'})};}});assert.equal(await mailer.sendDocument({email:'lab@example.test',subject:'Bilan',text:'Bonjour',fileName:'x.pdf',bytes}),'gmail-id');assert.ok(Buffer.from(sent.raw,'base64url').toString().includes(bytes.toString('base64')));});
test('Challenges : accès, PDF conservé, validation révisée et anti-double envoi',async t=>{
 let stored={id:1,...challenge,gain_per_collaborator:25,laboratory_id:1,laboratory_name:'Labo',laboratory_details:{labEmail:'lab@example.test'},results:null,report_id:null,revision:1},reports=[],sent=0;
 const db={connect:async()=>({...db,release(){}}),query:async(sql,a=[])=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return {rows:[]};if(sql.startsWith('SELECT c.'))return {rows:[stored]};if(sql.startsWith('INSERT INTO challenge_reports')){const report={id:reports.length+1,challenge_id:a[0],file_name:a[1],file_content:a[2],analysis:JSON.parse(a[3]),challenge_revision:a[4],send_status:'none'};reports.push(report);return {rows:[{id:report.id}]};}if(sql.startsWith('SELECT id,challenge_revision FROM challenge_reports'))return {rows:reports.filter(r=>r.id===Number(a[1])&&r.challenge_id===a[0])};if(sql.startsWith('UPDATE team_challenges SET results')){if(stored.revision!==a[3])return {rows:[]};stored={...stored,results:JSON.parse(a[1]),report_id:a[2],revision:stored.revision+1};return {rows:[{id:1}]};}if(sql.startsWith('UPDATE challenge_reports SET analysis')){Object.assign(reports.find(r=>r.id===a[0]),{analysis:JSON.parse(a[1]),confirmed_at:new Date()});return {rows:[]};}if(sql.startsWith("UPDATE challenge_reports SET send_status='sending'")){const r=reports.find(r=>r.id===Number(a[1])&&r.challenge_id===a[0]&&r.send_status==='none');if(!r)return {rows:[]};r.send_status='sending';return {rows:[r]};}if(sql.startsWith("UPDATE challenge_reports SET send_status='sent'")){Object.assign(reports.find(r=>r.id===Number(a[0])),{send_status:'sent',sent_at:new Date()});return {rows:[]};}throw Error('Unexpected SQL '+sql);}};
 const app=express();app.use((req,res,next)=>{req.auth={id:1,role:'admin'};next();});app.use((req,res,next)=>req.path.endsWith('/reports')&&req.method==='POST'?next():express.json()(req,res,next));const pass=(q,s,n)=>n(),access=()=> (q,s,n)=>q.headers['x-deny']?n(fail(403,'Accès refusé')):n(),csrf=(q,s,n)=>q.headers['x-csrf-token']==='ok'?n():n(fail(403,'CSRF'));registerChallenges({app,db,auth:pass,ready:pass,csrf,viewUniverse:access,editUniverse:access,fail,secret:'test',mailer:{status:async()=>({connected:true,sender:'pharmacie.trevoux@gmail.com'}),sendDocument:async()=>{sent++;return 'id';}}});app.use((e,q,s,n)=>s.status(e.status||500).json({error:e.message}));const server=app.listen(0);t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port,post=(path,body,extra={})=>fetch(base+path,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':'ok',...extra},body:JSON.stringify(body)});assert.equal((await fetch(base+'/api/challenges?month=2026-10',{headers:{'x-deny':'yes'}})).status,403);const pdf=await PDFDocument.create();pdf.addPage();const bytes=Buffer.from(await pdf.save()),upload={fileName:'bilan.pdf',fileData:bytes.toString('base64'),revision:1,analyze:false};assert.equal((await post('/api/challenges/1/reports',upload,{'x-csrf-token':'bad'})).status,403);const report=await(await post('/api/challenges/1/reports',upload)).json();assert.equal(report.id,1);assert.equal(stored.results,null);assert.deepEqual(reports[0].file_content,bytes);const results={global:50,participants:[{id:2,value:20},{id:3,value:30}],notes:[],revision:1};assert.equal((await post('/api/challenges/1/reports/1/confirm',results)).status,200);assert.equal(stored.results.global,50);assert.equal((await post('/api/challenges/1/reports/1/confirm',results)).status,409);assert.equal((await post('/api/challenges/1/reports/1/send',{email:'other@example.test'})).status,409);assert.equal((await post('/api/challenges/1/reports/1/send',{email:'lab@example.test'})).status,200);assert.equal((await post('/api/challenges/1/reports/1/send',{email:'lab@example.test'})).status,409);assert.equal(sent,1);
});
test('Challenges : gain enregistré, mise à jour sans perdre les ventes et seuil collectif',async t=>{
 let row;const db={query:async(sql,a=[])=>{
  if(sql.startsWith('SELECT id FROM laboratories'))return{rows:[{id:1}]};if(sql.startsWith('SELECT id,name,active'))return{rows:[{id:2,name:'Alice',active:true}]};
  if(sql.startsWith('INSERT INTO team_challenges')){assert.match(sql,/gain_per_collaborator/);row={id:1,month:a[0],title:a[1],laboratory_id:a[2],laboratory_name:'Labo',modalities:a[3],metric:a[4],target:a[5],participants:JSON.parse(a[6]),gain_per_collaborator:a[8],revision:1,results:null,report_id:null};return{rows:[{id:1}]};}
  if(sql.startsWith('SELECT c.'))return{rows:[row]};
  if(sql.startsWith('UPDATE team_challenges SET month')){assert.match(sql,/gain_per_collaborator=\$12/);if(a[10]!==row.revision)return{rows:[]};Object.assign(row,{target:a[6],participants:JSON.parse(a[7]),results:JSON.parse(a[8]),gain_per_collaborator:a[11],revision:row.revision+1});return{rows:[{id:1}]};}throw Error(sql);
 }};
 const app=express();app.use(express.json());const pass=(q,s,n)=>{q.auth={id:1,role:'admin'};n();};registerChallenges({app,db,auth:pass,ready:pass,csrf:pass,viewUniverse:()=>pass,editUniverse:()=>pass,fail,secret:'test',mailer:{}});app.use((e,q,s,n)=>s.status(e.status||500).json({error:e.message}));const server=app.listen(0);t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port;
 const save=(path,method,body)=>fetch(base+path,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)}),payload={...challenge,participants:[{id:2}],gainPerCollaborator:35.5};
 const created=await(await save('/api/challenges','POST',payload)).json();assert.equal(created.gainPerCollaborator,35.5);assert.equal(created.earnedPerCollaborator,0);assert.deepEqual(created.participants,[{id:2,name:'Alice'}]);
 row.results={global:150,participants:[{id:2,value:150}],notes:[]};
 const updated=await(await save('/api/challenges/1','PUT',{...payload,gainPerCollaborator:50,revision:1})).json();assert.equal(updated.earnedPerCollaborator,50);assert.equal(updated.results.global,150);
 const below=await(await save('/api/challenges/1','PUT',{...payload,target:151,gainPerCollaborator:50,revision:2})).json();assert.equal(below.earnedPerCollaborator,0);assert.equal(below.results.global,150);
 assert.equal((await save('/api/challenges/1','PUT',{...payload,gainPerCollaborator:-5,revision:3})).status,400);
});
