import test from 'node:test';import assert from 'node:assert/strict';import {validateLaboratory,registerLaboratories} from '../laboratories.mjs';import {canAccess,canModify} from '../security.mjs';import express from 'express';
const fail=(status,message)=>Object.assign(Error(message),{status});
test('Laboratoires : validations, responsable conditionnel et adresses sûres',()=>{
 const base={name:' Labo ',orderMode:'pharmacie',responsibleId:2};assert.equal(validateLaboratory(base,fail).name,'Labo');assert.throws(()=>validateLaboratory({...base,responsibleId:null},fail));assert.equal(validateLaboratory({...base,orderMode:'groupement'},fail).responsibleId,null);assert.throws(()=>validateLaboratory({...base,commercialEmail:'invalid'},fail));assert.throws(()=>validateLaboratory({...base,labWebsite:'javascript:alert(1)'},fail));assert.throws(()=>validateLaboratory({...base,conditions:'x'.repeat(4001)},fail));
 const user={role:'employee',rights:[],permissions_configured:false};assert.ok(canAccess(user,'Laboratoires'));assert.ok(canModify(user,'Laboratoires'));assert.equal(canModify({...user,permissions_configured:true},'Laboratoires'),false);
});
test('Laboratoires : accès équipe, création et protection contre écrasement concurrent',async t=>{
 const app=express();app.use(express.json());let row=null,allowed=true;const pass=(req,res,next)=>{req.auth={id:1};next();},access=()=>((req,res,next)=>allowed?next():res.sendStatus(403));
 const db={query:async(sql,args)=>{if(sql.startsWith('SELECT id FROM users'))return {rows:args[0]===2?[{id:2}]:[]};if(sql.startsWith('INSERT INTO laboratories')){row={id:1,name:args[0],order_mode:args[1],responsible_id:args[2],details:JSON.parse(args[3]),revision:1};return {rows:[row]};}if(sql.startsWith('UPDATE laboratories')){if(args[6]!==row.revision)return {rows:[]};row={...row,name:args[1],order_mode:args[2],responsible_id:args[3],details:JSON.parse(args[4]),revision:row.revision+1};return {rows:[row]};}return {rows:row?[row]:[]};}};
 registerLaboratories({app,db,auth:pass,ready:pass,csrf:pass,viewUniverse:access,fail,publish:async()=>{}});app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0);t.after(()=>server.close());const url='http://127.0.0.1:'+server.address().port+'/api/laboratories';const body={name:'Labo',orderMode:'pharmacie',responsibleId:2,commercialEmail:'representant@example.test'};
 let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,201);assert.equal((await r.json()).commercialEmail,body.commercialEmail);
 r=await fetch(url+'/1',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,revision:1,orderMode:'groupement'})});assert.equal(r.status,200);assert.equal((await r.json()).responsibleId,null);
 r=await fetch(url+'/1',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,revision:1})});assert.equal(r.status,409);allowed=false;assert.equal((await fetch(url)).status,403);
});
