import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {validateTemplateDay,applyTemplate} from '../schedule-templates.mjs';import {registerSchedule,copySchedule,validateDay} from '../schedule.mjs';
const fail=(status,message)=>Object.assign(Error(message),{status}),entry={userId:2,weekday:0,kind:'travail',slots:[['08:00','12:00'],['14:00','18:00']],postIds:[7,null]};
test('Semaine type sans dates, affectations préservées, utilisateurs actifs et tickets non recopiés',()=>{const model=validateTemplateDay({...entry,mealTicket:true});assert.equal(model.day,undefined);assert.equal(model.mealTicket,undefined);assert.equal(model.weekday,0);assert.throws(()=>validateTemplateDay({...entry,weekday:7}));const applied=applyTemplate({a:model,b:{...model,userId:3,weekday:1}},'2026-10-12',[2]);assert.deepEqual(Object.keys(applied),['2:2026-10-12']);assert.deepEqual(applied['2:2026-10-12'].postIds,[7,null]);assert.equal(applied['2:2026-10-12'].mealTicket,false);const copied=copySchedule({a:{...model,day:'2026-10-05',mealTicket:true}},'2026-10-05','2026-10-12',[2]);assert.equal(copied['2:2026-10-12'].mealTicket,undefined);for(const kind of ['conge','maladie','recuperation','absence_injustifiee'])assert.equal(validateDay({userId:2,day:'2026-10-05',kind,slots:[]},'2026-10-05').kind,kind);assert.throws(()=>validateDay({userId:2,day:'2026-10-05',kind:'repos',slots:[],mealTicket:'true'},'2026-10-05'));});
test('Modèles et tickets administrateur, application au brouillon, révisions et confidentialité des absences',async t=>{
 let actor={id:1,role:'admin'},models=new Map(),weeks=new Map(),next=0;const people=[{id:1,name:'Admin'},{id:2,name:'Salarié'}];
 const db={query:async(sql,a=[])=>{
  if(sql.startsWith('SELECT id,name,job FROM users'))return {rows:people};
  if(sql.startsWith('SELECT id,active FROM schedule_posts'))return {rows:a[0].filter(id=>id===7).map(id=>({id,active:true}))};
  if(sql.startsWith('SELECT id,name,revision FROM schedule_templates'))return {rows:[...models.values()]};
  if(sql.startsWith('SELECT id,name,content,revision FROM schedule_templates'))return {rows:models.has(a[0])?[models.get(a[0])]:[]};
  if(sql.startsWith('INSERT INTO schedule_templates')){const r={id:++next,name:a[0],revision:1,content:{}};models.set(r.id,r);return {rows:[r]};}
  if(sql.startsWith('UPDATE schedule_templates SET content=jsonb_set')){const r=models.get(a[2]);if(!r||r.revision!==a[3])return {rows:[]};r.content[a[0]]=JSON.parse(a[1]);r.revision++;return {rows:[{revision:r.revision}]};}
  if(sql.startsWith('UPDATE schedule_templates SET content=content-')){const r=models.get(a[1]);if(!r||r.revision!==a[2])return {rows:[]};delete r.content[a[0]];r.revision++;return {rows:[{revision:r.revision}]};}
  if(sql.startsWith('UPDATE schedule_templates SET name')){const r=models.get(a[0]);if(!r||r.revision!==a[2])return {rows:[]};r.name=a[1];r.revision++;return {rows:[r]};}
  if(sql.startsWith('DELETE FROM schedule_templates')){const r=models.get(a[0]);if(!r||r.revision!==a[1])return {rows:[]};models.delete(r.id);return {rows:[{id:r.id}]};}
  if(sql.startsWith('SELECT * FROM schedule_weeks'))return {rows:weeks.has(a[0])?[weeks.get(a[0])]:[]};
  if(sql.startsWith('INSERT INTO schedule_weeks')){if(!weeks.has(a[0]))weeks.set(a[0],{week:a[0],draft:{},published:{},revision:0});return {rows:[]};}
  if(sql.startsWith('UPDATE schedule_weeks SET draft=$1')){const r=weeks.get(a[1]);if(r.revision!==a[2])return {rows:[]};r.draft=JSON.parse(a[0]);r.revision++;return {rows:[{revision:r.revision}]};}
  if(sql.includes('UPDATE schedule_weeks SET draft=jsonb_set')){const r=weeks.get(a[2]);if(r.revision!==a[3])return {rows:[]};r.draft[a[0]]=JSON.parse(a[1]);r.revision++;return {rows:[{revision:r.revision}]};}
  throw Error(sql);
 }};
 const app=express();app.use(express.json());const auth=(req,res,next)=>{req.auth=actor;next();},pass=(req,res,next)=>next(),admin=(req,res,next)=>actor.role==='admin'?next():next(fail(403,'Admin')),csrf=(req,res,next)=>req.headers['x-csrf-token']==='test'?next():next(fail(403,'CSRF'));
 registerSchedule({app,db,auth,ready:pass,admin,csrf,canAccess:()=>true,canModify:u=>u.role==='admin'||u.editor,fail});app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0);t.after(()=>server.close());const req=(path,body,method='POST',token='test')=>fetch('http://127.0.0.1:'+server.address().port+path,body===undefined?{}:{method,headers:{'content-type':'application/json','x-csrf-token':token},body:JSON.stringify(body)});
 assert.equal((await req('/api/schedule-templates',{name:'Semaine paire'},'POST','wrong')).status,403);assert.equal((await req('/api/schedule-templates',{name:'Semaine paire'})).status,201);assert.equal((await req('/api/schedule-templates/1/day',{...entry,revision:1},'PUT')).status,200);assert.equal(weeks.size,0);assert.equal((await req('/api/schedule-templates/1/day',{...entry,revision:1},'PUT')).status,409);
 assert.equal((await req('/api/schedule/2026-10-12/apply-template',{templateId:1,templateRevision:1,revision:0})).status,409);assert.equal((await req('/api/schedule/2026-10-12/apply-template',{templateId:1,templateRevision:2,revision:0})).status,200);const w=weeks.get('2026-10-12');assert.deepEqual(w.published,{});assert.equal(w.draft['2:2026-10-12'].postIds[0],7);assert.equal(w.draft['2:2026-10-12'].mealTicket,false);
 assert.equal((await req('/api/schedule/2026-10-12/meal-ticket',{userId:2,day:'2026-10-12',enabled:true,revision:1})).status,200);assert.equal(w.draft['2:2026-10-12'].mealTicket,true);assert.deepEqual(w.draft['2:2026-10-12'].slots,entry.slots);assert.equal((await req('/api/schedule/2026-10-12/meal-ticket',{userId:2,day:'2026-10-12',enabled:false,revision:1})).status,409);
 assert.equal((await req('/api/schedule/2026-10-12/day',{userId:2,day:'2026-10-12',kind:'maladie',slots:[],revision:2},'PUT')).status,200);assert.equal(w.draft['2:2026-10-12'].mealTicket,true);w.published=structuredClone(w.draft);w.published['1:2026-10-13']={userId:1,day:'2026-10-13',kind:'absence_injustifiee',slots:[],mealTicket:true};
 actor={id:2,role:'employee'};assert.equal((await req('/api/schedule-templates')).status,403);assert.equal((await req('/api/schedule/2026-10-12/meal-ticket',{userId:2,day:'2026-10-12',enabled:false,revision:3})).status,403);const visible=await (await req('/api/schedule?week=2026-10-12&scope=team')).json();assert.equal(visible.entries.find(e=>e.userId===2).kind,'maladie');assert.equal(visible.entries.find(e=>e.userId===1).kind,'absence');assert.equal(visible.entries.find(e=>e.userId===1).mealTicket,undefined);assert.equal(w.published['1:2026-10-13'].kind,'absence_injustifiee');
 actor={id:2,role:'employee',editor:true};assert.equal((await req('/api/schedule/2026-10-12/day',{userId:2,day:'2026-10-12',kind:'travail',slots:[['08:00','09:00']],revision:3},'PUT')).status,403);assert.equal((await req('/api/schedule/2026-10-12/apply-template',{templateId:1,templateRevision:2,revision:3})).status,403);
 actor={id:1,role:'admin'};assert.equal((await req('/api/schedule-templates/1/clear-day',{userId:2,weekday:0,revision:2})).status,200);assert.equal((await req('/api/schedule-templates/1',{name:'Semaine impaire',revision:3},'PUT')).status,200);assert.equal((await req('/api/schedule-templates/1',{revision:4},'DELETE')).status,200);assert.equal(w.draft['2:2026-10-12'].kind,'maladie');
});
