import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {validatePost,validateLeave,registerScheduleTools} from '../schedule-tools.mjs';
const fail=(status,message)=>Object.assign(Error(message),{status});const leave={leaveType:'Congés payés',startDate:'2026-11-02',endDate:'2026-11-06',startPart:'full',endPart:'full',comment:'Demande test'};
test('Postes et demandes : couleurs sûres, périodes et demi-journées valides',()=>{assert.equal(validatePost({name:' Comptoir ',color:'#AA1133'}).name,'Comptoir');assert.throws(()=>validatePost({name:'Poste',color:'red;display:none'}));assert.equal(validateLeave(leave).endDate,'2026-11-06');assert.throws(()=>validateLeave({...leave,endDate:'2026-10-01'}));assert.throws(()=>validateLeave({...leave,startDate:'2026-02-30'}));assert.throws(()=>validateLeave({...leave,endDate:leave.startDate,endPart:'afternoon'}));assert.throws(()=>validateLeave({...leave,userId:2,comment:'a'.repeat(1201)}));});
test('Demandes privées, identité serveur, décision administrateur, révisions et postes réservés aux administrateurs',async t=>{
 let actor={id:1,role:'employee'},items=[],posts=[],counter=0;const db={query:async(sql,a=[])=>{
  if(sql.startsWith('SELECT l.id'))return {rows:items.filter(r=>!sql.includes('WHERE l.user_id=$1')||r.user_id===a[0])};
  if(sql.startsWith('INSERT INTO leave_requests')){if(items.some(r=>r.user_id===a[0]&&r.status==='pending'&&r.start_date===a[2]))throw Object.assign(Error(),{code:'23505'});const r={id:++counter,user_id:a[0],leave_type:a[1],start_date:a[2],end_date:a[3],start_part:a[4],end_part:a[5],comment:a[6],status:'pending',revision:1};items.push(r);return {rows:[r]};}
  if(sql.startsWith('UPDATE leave_requests SET status=\'cancelled')){const r=items.find(r=>r.id===a[0]&&r.user_id===a[1]&&r.revision===a[2]&&r.status==='pending');if(!r)return {rows:[]};r.status='cancelled';r.revision++;return {rows:[r]};}
  if(sql.startsWith('UPDATE leave_requests SET status=$2')){const r=items.find(r=>r.id===a[0]&&r.revision===a[4]&&r.status==='pending'&&r.user_id!==a[3]);if(!r)return {rows:[]};r.status=a[1];r.review_note=a[2];r.reviewed_by=a[3];r.revision++;return {rows:[r]};}
  if(sql.startsWith('SELECT id,name'))return {rows:posts};if(sql.startsWith('SELECT id,active FROM schedule_posts'))return {rows:posts.filter(p=>a[0].includes(p.id))};
  if(sql.startsWith('INSERT INTO schedule_posts')){const p={id:posts.length+1,name:a[0],color:a[1],active:a[2],revision:1};posts.push(p);return {rows:[p]};}
  if(sql.startsWith('UPDATE schedule_posts SET name')){const p=posts.find(p=>p.id===a[0]&&p.revision===a[4]);if(!p)return {rows:[]};Object.assign(p,{name:a[1],color:a[2],active:a[3],revision:p.revision+1});return {rows:[p]};}
  throw Error(sql);
 }};
 const app=express();app.use(express.json());const auth=(req,res,next)=>{req.auth=actor;next();},pass=(req,res,next)=>next(),admin=(req,res,next)=>actor.role==='admin'?next():next(fail(403,'Admin')),csrf=(req,res,next)=>req.headers['x-csrf-token']==='test'?next():next(fail(403,'CSRF'));
 const tools=registerScheduleTools({app,db,auth,ready:pass,admin,csrf,canAccess:()=>true,fail});app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0);t.after(()=>server.close());const request=(path,body,method='POST',token='test')=>fetch('http://127.0.0.1:'+server.address().port+path,body===undefined?{}:{method,headers:{'content-type':'application/json','x-csrf-token':token},body:JSON.stringify(body)});
 assert.equal((await request('/api/leave-requests',leave,'POST','wrong')).status,403);assert.equal((await request('/api/schedule-posts',{name:'Comptoir',color:'#aabbcc'})).status,403);
 assert.equal((await request('/api/leave-requests',{...leave,userId:2})).status,201);assert.equal(items[0].user_id,1);assert.equal((await request('/api/leave-requests',leave)).status,409);assert.equal((await request('/api/leave-requests?scope=team')).status,403);
 actor={id:2,role:'employee'};assert.deepEqual(await (await request('/api/leave-requests')).json(),[]);assert.equal((await request('/api/leave-requests/1/cancel',{revision:1})).status,409);assert.equal((await request('/api/leave-requests/1/review',{revision:1,status:'approved',note:''})).status,403);assert.equal((await request('/api/leave-requests',{...leave,startDate:'2026-12-01',endDate:'2026-12-02'})).status,201);
 actor={id:3,role:'admin'};assert.equal((await (await request('/api/leave-requests?scope=team')).json()).length,2);assert.equal((await request('/api/leave-requests/1/review',{revision:1,status:'approved',note:'Accord'})).status,200);assert.equal((await request('/api/leave-requests/1/review',{revision:1,status:'refused',note:''})).status,409);assert.equal(items[0].reviewed_by,3);
 assert.equal((await request('/api/schedule-posts',{name:'Comptoir',color:'#aabbcc'})).status,201);await tools.validatePostIds({postIds:[1,null,1]});await assert.rejects(()=>tools.validatePostIds({postIds:[99]}));assert.equal((await request('/api/schedule-posts/1',{name:'Comptoir',color:'#335577',active:false,revision:1},'PUT')).status,200);assert.equal(posts[0].active,false);await assert.rejects(()=>tools.validatePostIds({postIds:[1]}));await tools.validatePostIds({postIds:[1]}, {postIds:[1]});await assert.rejects(()=>tools.validatePostIds({postIds:[1,1]},{postIds:[1]}));assert.equal((await request('/api/schedule-posts/1',{name:'Comptoir',color:'#335577',revision:1},'PUT')).status,409);
 actor={id:1,role:'employee'};assert.equal((await (await request('/api/leave-requests')).json()).length,1);assert.equal((await request('/api/leave-requests/1/cancel',{revision:2})).status,409);actor={id:2,role:'employee'};assert.equal((await request('/api/leave-requests/2/cancel',{revision:1})).status,200);
});
